version: '3.7'

services:
  consul:
    image: consul
    ports:
      - "8400"
      - "8600"
      - "8600/udp"
      - "8301"
      - "8302"
      - "8301/udp"
      - "8302/udp"
    command: "consul agent -disable-host-node-id -client=0.0.0.0 -bind '{{ GetInterfaceIP \"eth0\" }}' -retry-join 192.168.2.74 -data-dir /consul/data -config-dir /consul/config"
  eip-restlet:
    image:  chenxinma/eip-restlet:0.0.1-SNAPSHOT
    ports:
      - "8080:8080"
    links:
      - "consul"