version: '3.7'

services:
  consul:
    image: consul
    ports:
      - "8400:8400"
      - "8500:8500"
      - "8600:8600"
  eip-restlet:
    image:  chenxinma/eip-restlet:0.0.1-SNAPSHOT
    ports:
      - "8080:8080"
    links:
      - "consul"